# Generated by Django 4.2.6 on 2023-10-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setsong',
            unique_together={('setlist', 'sort_order')},
        ),
    ]
