# Generated by Django 4.2.6 on 2023-11-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtaildocs", "0012_uploadeddocument"),
        ("setlist", "0002_alter_setsong_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="song",
            options={"ordering": ("title",)},
        ),
        migrations.AddField(
            model_name="song",
            name="recordings",
            field=models.ManyToManyField(blank=True, to="wagtaildocs.document"),
        ),
    ]
