# Generated by Django 4.2.6 on 2023-10-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_show_set_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
